name: Debug Workflow
on:
    workflow_dispatch: 
jobs:
    debug1:
        name: Debug1
        runs-on: ubuntu-latest
        steps:
            - name: Checkout local git
              uses: actions/checkout@v4
            - name: Debug Instance Specs
              run: |
                echo "${{ secrets.INSTANCE_SPECS }}" > instance.txt
                cat instance.txt