name: Destroy Resources
on:
  workflow_run: 
    workflows: ["Release Instance ENV"]
    types: completed
  workflow_dispatch: 

jobs:
  Destroy-VM:
    environment: MyLAB
    runs-on: ubuntu-latest
    steps:
      - name: Destroy Instance/VM Only
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.INSTANCE_DIR }}/${{ github.repository }}/${{ vars.VM_NAME }}
            terraform destroy -auto-approve
  Destroy-All:
    environment: MyLAB
    needs: Destroy-VM
    runs-on: ubuntu-latest
    steps:
      - name: Destroy All Resources
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export POOL="${{ vars.POOL }}"
            export POOLDIR=${{ vars.POOLDIR }}
            export POOL_IMG=${{ vars.POOL_IMG }}
            export NETWORK_DIR=${{ secrets.NETWORK_DIR }}
            export OS_IMG=${{ vars.OS_IMG }}
            source ${{ secrets.INSTANCE_DIR }}/scripts/setup/instance.sh
            destroy_img
            destroy_net